# Generated by Django 6.0.1 on 2026-02-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('descriptions', models.TextField(verbose_name='Tavsif')),
                ('episodes', models.IntegerField(verbose_name='Epizdlar soni')),
                ('release_date', models.DateField(verbose_name='Chiqgan sana')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgs/', verbose_name='Rasim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animelar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(verbose_name='Epizod raqami')),
                ('video', models.FileField(upload_to='episodes/videos/', verbose_name='Video fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodeslar', to='anime.animes', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Epizod',
                'verbose_name_plural': 'Epizodlar',
                'ordering': ['anime', 'episode_number'],
                'unique_together': {('anime', 'episode_number')},
            },
        ),
    ]
